<div class="tabnav">
    <ul class="tabnav-tabs">
        <li><a class="tabnav-tab selected" href="<?=$this->url('zfcuser')?>">Account Information</a></li>
        <li><a class="tabnav-tab" href="<?=$this->url('zfcuser/addresses')?>">Address Book</a></li>
        <li><a class="tabnav-tab" href="<?=$this->url('zfcuser/changeemail')?>">Change Email</a></li>
        <li><a class="tabnav-tab" href="<?=$this->url('zfcuser/changepassword')?>">Change Password</a></li>
    </ul>
</div>

The following is your account info. This includes your account login (your email address) and billing information.
<div class="dashboard-content">
<dl>
    <dt>Account Login:</dt>
    <dd><?=$this->zfcUserIdentity()->getEmail()?></dd>

    <dt>Account Number:</dt>
    <dd><?=$this->zfcUserIdentity()->getId()?></d>

    <dt>Billing Name:</dt>
    <dd>???</dd>

    <dt>Default Billing Address:</dt>
    <dd>???</dd>
</dl>
</div>
